/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Result_2 = {
    __kind__: "ok";
    ok: UserCollection;
} | {
    __kind__: "err";
    err: string;
};
export interface NftRecord {
    imageBlob: ExternalBlob;
    ownerAddress: string;
    collectionId: string;
    name: string;
    description: string;
    mintedAt: Timestamp;
    listingStatus: ListingStatus;
    attributes: Array<[string, string]>;
    mintAddress: string;
}
export type ListingStatus = {
    __kind__: "fixedPrice";
    fixedPrice: bigint;
} | {
    __kind__: "auction";
    auction: AuctionId;
} | {
    __kind__: "unlisted";
    unlisted: null;
};
export interface Bid {
    txSignature: string;
    placedAt: Timestamp;
    amount: number;
    bidder: string;
}
export interface AppConfig {
    collectionCreationFeeSOL: number;
    solanaRpcUrl: string;
    network: string;
    escrowWalletAddress: string;
    platformFeePercent: number;
}
export type Result_5 = {
    __kind__: "ok";
    ok: NftRecord;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Bid;
} | {
    __kind__: "err";
    err: string;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserCollectionInput {
    metadataUri: string;
    imageBlob: ExternalBlob;
    name: string;
    description: string;
    mintAuthority: string;
    collectionMintAddress: string;
    symbol: string;
}
export interface UserCollection {
    id: string;
    metadataUri: string;
    imageBlob: ExternalBlob;
    ownerAddress: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    mintCount: bigint;
    mintAuthority: string;
    collectionMintAddress: string;
    collectionFeeSOL: number;
    symbol: string;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Auction;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type AuctionId = string;
export interface NftInput {
    imageBlob: ExternalBlob;
    collectionId: string;
    name: string;
    description: string;
    attributes: Array<[string, string]>;
    mintAddress: string;
}
export interface Listing {
    id: string;
    status: ListingStatus__1;
    expiresAt: Timestamp;
    listedAt: Timestamp;
    mintAddress: string;
    priceSOL: number;
    sellerAddress: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Listing;
} | {
    __kind__: "err";
    err: string;
};
export interface ListingFilter {
    status?: ListingStatus__1;
    mintAddress?: string;
    sellerAddress?: string;
}
export interface Collection {
    id: string;
    metadataProgramAddress: string;
    imageBlob: ExternalBlob;
    name: string;
    createdAt: Timestamp;
    createdBy: string;
    description: string;
    mintAddress: string;
}
export interface AuctionFilter {
    status?: AuctionStatus;
    mintAddress?: string;
    sellerAddress?: string;
}
export interface Auction {
    id: string;
    status: AuctionStatus;
    bids: Array<Bid>;
    startsAt: Timestamp;
    currentHighestBid?: number;
    reservePriceSOL: number;
    currentHighestBidder?: string;
    mintAddress: string;
    startPriceSOL: number;
    sellerAddress: string;
    endsAt: Timestamp;
}
export interface UserProfile {
    createdCollections: Array<string>;
    joinedAt: Timestamp;
    role: Role;
    solanaAddress: string;
}
export interface CollectionInput {
    metadataProgramAddress: string;
    imageBlob: ExternalBlob;
    name: string;
    description: string;
    mintAddress: string;
}
export enum AuctionStatus {
    active = "active",
    cancelled = "cancelled",
    settled = "settled",
    pending = "pending",
    ended = "ended"
}
export enum ListingStatus__1 {
    active = "active",
    cancelled = "cancelled",
    expired = "expired",
    sold = "sold"
}
export enum Role {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addNftToUserCollection(collectionId: string, nft: NftInput): Promise<Result_5>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelAuction(auctionId: string): Promise<Result>;
    cancelListing(listingId: string): Promise<Result>;
    completeSale(listingId: string, buyerAddress: string, txSignature: string): Promise<Result>;
    createAuction(mintAddress: string, startPriceSOL: number, reservePriceSOL: number, durationHours: bigint): Promise<Result_4>;
    createListing(mintAddress: string, priceSOL: number, durationDays: bigint): Promise<Result_3>;
    createUserCollection(data: UserCollectionInput, txSignature: string): Promise<Result_2>;
    deleteCollection(id: string): Promise<Result>;
    getAuction(auctionId: string): Promise<Auction | null>;
    getAuctions(filter: AuctionFilter | null): Promise<Array<Auction>>;
    getCallerUserRole(): Promise<UserRole>;
    getCollections(): Promise<Array<Collection>>;
    getConfig(): Promise<AppConfig>;
    getListings(filter: ListingFilter | null): Promise<Array<Listing>>;
    getMyRole(): Promise<Role>;
    getNft(mintAddress: string): Promise<NftRecord | null>;
    /**
     * / Query Solana Devnet balance for a given address; returns lamports as Text.
     */
    getSolanaBalance(address: string): Promise<string>;
    getUser(solanaAddress: string): Promise<UserProfile | null>;
    getUserCollections(ownerAddress: string): Promise<Array<UserCollection>>;
    getUserNfts(ownerAddress: string): Promise<Array<NftRecord>>;
    isCallerAdmin(): Promise<boolean>;
    placeBid(auctionId: string, bidAmountSOL: number, bidderAddress: string, txSignature: string): Promise<Result_1>;
    registerCollection(data: CollectionInput): Promise<string>;
    registerUser(solanaAddress: string): Promise<Role>;
    settleAuction(auctionId: string, winnerAddress: string, paymentTxSignature: string): Promise<Result>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCollection(id: string, data: CollectionInput): Promise<Result>;
    updateConfig(config: AppConfig): Promise<Result>;
    /**
     * / Verify a Solana transaction is finalized; returns raw JSON response as Text.
     */
    verifyTransaction(txSignature: string): Promise<string>;
}
import type { Auction as _Auction, AuctionFilter as _AuctionFilter, AuctionId as _AuctionId, AuctionStatus as _AuctionStatus, Bid as _Bid, Collection as _Collection, CollectionInput as _CollectionInput, ExternalBlob as _ExternalBlob, Listing as _Listing, ListingFilter as _ListingFilter, ListingStatus as _ListingStatus, ListingStatus__1 as _ListingStatus__1, NftInput as _NftInput, NftRecord as _NftRecord, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Role as _Role, Timestamp as _Timestamp, UserCollection as _UserCollection, UserCollectionInput as _UserCollectionInput, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addNftToUserCollection(arg0: string, arg1: NftInput): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.addNftToUserCollection(arg0, await to_candid_NftInput_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_5_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNftToUserCollection(arg0, await to_candid_NftInput_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_5_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelAuction(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAuction(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAuction(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelListing(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelListing(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelListing(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeSale(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.completeSale(arg0, arg1, arg2);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeSale(arg0, arg1, arg2);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAuction(arg0: string, arg1: number, arg2: number, arg3: bigint): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createAuction(arg0, arg1, arg2, arg3);
                return from_candid_Result_4_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAuction(arg0, arg1, arg2, arg3);
            return from_candid_Result_4_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createListing(arg0: string, arg1: number, arg2: bigint): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2);
                return from_candid_Result_3_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2);
            return from_candid_Result_3_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUserCollection(arg0: UserCollectionInput, arg1: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserCollection(await to_candid_UserCollectionInput_n36(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Result_2_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserCollection(await to_candid_UserCollectionInput_n36(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Result_2_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCollection(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuction(arg0: string): Promise<Auction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuction(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuction(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuctions(arg0: AuctionFilter | null): Promise<Array<Auction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuctions(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuctions(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollections(): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollections();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollections();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfig(): Promise<AppConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfig();
            return result;
        }
    }
    async getListings(arg0: ListingFilter | null): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings(to_candid_opt_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings(to_candid_opt_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<Role> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_Role_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_Role_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNft(arg0: string): Promise<NftRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNft(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNft(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSolanaBalance(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSolanaBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSolanaBalance(arg0);
            return result;
        }
    }
    async getUser(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCollections(arg0: string): Promise<Array<UserCollection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCollections(arg0);
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCollections(arg0);
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserNfts(arg0: string): Promise<Array<NftRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNfts(arg0);
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNfts(arg0);
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeBid(arg0: string, arg1: number, arg2: string, arg3: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBid(arg0, arg1, arg2, arg3);
                return from_candid_Result_1_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBid(arg0, arg1, arg2, arg3);
            return from_candid_Result_1_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCollection(arg0: CollectionInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCollection(await to_candid_CollectionInput_n69(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCollection(await to_candid_CollectionInput_n69(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerUser(arg0: string): Promise<Role> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return from_candid_Role_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return from_candid_Role_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async settleAuction(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.settleAuction(arg0, arg1, arg2);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.settleAuction(arg0, arg1, arg2);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCollection(arg0: string, arg1: CollectionInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollection(arg0, await to_candid_CollectionInput_n69(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollection(arg0, await to_candid_CollectionInput_n69(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateConfig(arg0: AppConfig): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConfig(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConfig(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyTransaction(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyTransaction(arg0);
            return result;
        }
    }
}
function from_candid_AuctionStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuctionStatus): AuctionStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Auction_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Auction): Auction {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_Collection_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Collection): Promise<Collection> {
    return await from_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingStatus__1_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus__1): ListingStatus__1 {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_NftRecord_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NftRecord): Promise<NftRecord> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
async function from_candid_Result_2_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Promise<Result_2> {
    return await from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Result_5_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Promise<Result_5> {
    return await from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_UserCollection_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserCollection): Promise<UserCollection> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Auction]): Auction | null {
    return value.length === 0 ? null : from_candid_Auction_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NftRecord]): Promise<NftRecord | null> {
    return value.length === 0 ? null : await from_candid_NftRecord_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n63(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageBlob: _ExternalBlob;
    ownerAddress: string;
    collectionId: string;
    name: string;
    description: string;
    mintedAt: _Timestamp;
    listingStatus: _ListingStatus;
    attributes: Array<[string, string]>;
    mintAddress: string;
}): Promise<{
    imageBlob: ExternalBlob;
    ownerAddress: string;
    collectionId: string;
    name: string;
    description: string;
    mintedAt: Timestamp;
    listingStatus: ListingStatus;
    attributes: Array<[string, string]>;
    mintAddress: string;
}> {
    return {
        imageBlob: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.imageBlob),
        ownerAddress: value.ownerAddress,
        collectionId: value.collectionId,
        name: value.name,
        description: value.description,
        mintedAt: value.mintedAt,
        listingStatus: from_candid_ListingStatus_n16(_uploadFile, _downloadFile, value.listingStatus),
        attributes: value.attributes,
        mintAddress: value.mintAddress
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AuctionStatus;
    bids: Array<_Bid>;
    startsAt: _Timestamp;
    currentHighestBid: [] | [number];
    reservePriceSOL: number;
    currentHighestBidder: [] | [string];
    mintAddress: string;
    startPriceSOL: number;
    sellerAddress: string;
    endsAt: _Timestamp;
}): {
    id: string;
    status: AuctionStatus;
    bids: Array<Bid>;
    startsAt: Timestamp;
    currentHighestBid?: number;
    reservePriceSOL: number;
    currentHighestBidder?: string;
    mintAddress: string;
    startPriceSOL: number;
    sellerAddress: string;
    endsAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_AuctionStatus_n26(_uploadFile, _downloadFile, value.status),
        bids: value.bids,
        startsAt: value.startsAt,
        currentHighestBid: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.currentHighestBid)),
        reservePriceSOL: value.reservePriceSOL,
        currentHighestBidder: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.currentHighestBidder)),
        mintAddress: value.mintAddress,
        startPriceSOL: value.startPriceSOL,
        sellerAddress: value.sellerAddress,
        endsAt: value.endsAt
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ListingStatus__1;
    expiresAt: _Timestamp;
    listedAt: _Timestamp;
    mintAddress: string;
    priceSOL: number;
    sellerAddress: string;
}): {
    id: string;
    status: ListingStatus__1;
    expiresAt: Timestamp;
    listedAt: Timestamp;
    mintAddress: string;
    priceSOL: number;
    sellerAddress: string;
} {
    return {
        id: value.id,
        status: from_candid_ListingStatus__1_n34(_uploadFile, _downloadFile, value.status),
        expiresAt: value.expiresAt,
        listedAt: value.listedAt,
        mintAddress: value.mintAddress,
        priceSOL: value.priceSOL,
        sellerAddress: value.sellerAddress
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    metadataUri: string;
    imageBlob: _ExternalBlob;
    ownerAddress: string;
    name: string;
    createdAt: _Timestamp;
    description: string;
    mintCount: bigint;
    mintAuthority: string;
    collectionMintAddress: string;
    collectionFeeSOL: number;
    symbol: string;
}): Promise<{
    id: string;
    metadataUri: string;
    imageBlob: ExternalBlob;
    ownerAddress: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    mintCount: bigint;
    mintAuthority: string;
    collectionMintAddress: string;
    collectionFeeSOL: number;
    symbol: string;
}> {
    return {
        id: value.id,
        metadataUri: value.metadataUri,
        imageBlob: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.imageBlob),
        ownerAddress: value.ownerAddress,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        mintCount: value.mintCount,
        mintAuthority: value.mintAuthority,
        collectionMintAddress: value.collectionMintAddress,
        collectionFeeSOL: value.collectionFeeSOL,
        symbol: value.symbol
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    metadataProgramAddress: string;
    imageBlob: _ExternalBlob;
    name: string;
    createdAt: _Timestamp;
    createdBy: string;
    description: string;
    mintAddress: string;
}): Promise<{
    id: string;
    metadataProgramAddress: string;
    imageBlob: ExternalBlob;
    name: string;
    createdAt: Timestamp;
    createdBy: string;
    description: string;
    mintAddress: string;
}> {
    return {
        id: value.id,
        metadataProgramAddress: value.metadataProgramAddress,
        imageBlob: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.imageBlob),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        mintAddress: value.mintAddress
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdCollections: Array<string>;
    joinedAt: _Timestamp;
    role: _Role;
    solanaAddress: string;
}): {
    createdCollections: Array<string>;
    joinedAt: Timestamp;
    role: Role;
    solanaAddress: string;
} {
    return {
        createdCollections: value.createdCollections,
        joinedAt: value.joinedAt,
        role: from_candid_Role_n60(_uploadFile, _downloadFile, value.role),
        solanaAddress: value.solanaAddress
    };
}
async function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _NftRecord;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: NftRecord;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_NftRecord_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixedPrice: bigint;
} | {
    auction: _AuctionId;
} | {
    unlisted: null;
}): {
    __kind__: "fixedPrice";
    fixedPrice: bigint;
} | {
    __kind__: "auction";
    auction: AuctionId;
} | {
    __kind__: "unlisted";
    unlisted: null;
} {
    return "fixedPrice" in value ? {
        __kind__: "fixedPrice",
        fixedPrice: value.fixedPrice
    } : "auction" in value ? {
        __kind__: "auction",
        auction: value.auction
    } : "unlisted" in value ? {
        __kind__: "unlisted",
        unlisted: value.unlisted
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Auction;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Auction;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Auction_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    settled: null;
} | {
    pending: null;
} | {
    ended: null;
}): AuctionStatus {
    return "active" in value ? AuctionStatus.active : "cancelled" in value ? AuctionStatus.cancelled : "settled" in value ? AuctionStatus.settled : "pending" in value ? AuctionStatus.pending : "ended" in value ? AuctionStatus.ended : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Listing;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Listing;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Listing_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    sold: null;
}): ListingStatus__1 {
    return "active" in value ? ListingStatus__1.active : "cancelled" in value ? ListingStatus__1.cancelled : "expired" in value ? ListingStatus__1.expired : "sold" in value ? ListingStatus__1.sold : value;
}
async function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserCollection;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: UserCollection;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_UserCollection_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : "guest" in value ? Role.guest : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Bid;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Bid;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Auction>): Array<Auction> {
    return value.map((x)=>from_candid_Auction_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Collection>): Promise<Array<Collection>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Collection_n52(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n32(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserCollection>): Promise<Array<UserCollection>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserCollection_n40(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NftRecord>): Promise<Array<NftRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NftRecord_n13(_uploadFile, _downloadFile, x)));
}
function to_candid_AuctionFilter_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuctionFilter): _AuctionFilter {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_AuctionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuctionStatus): _AuctionStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_CollectionInput_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollectionInput): Promise<_CollectionInput> {
    return await to_candid_record_n70(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingFilter_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilter): _ListingFilter {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_ListingStatus__1_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus__1): _ListingStatus__1 {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
async function to_candid_NftInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NftInput): Promise<_NftInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_UserCollectionInput_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserCollectionInput): Promise<_UserCollectionInput> {
    return await to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuctionFilter | null): [] | [_AuctionFilter] {
    return value === null ? candid_none() : candid_some(to_candid_AuctionFilter_n44(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilter | null): [] | [_ListingFilter] {
    return value === null ? candid_none() : candid_some(to_candid_ListingFilter_n55(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadataUri: string;
    imageBlob: ExternalBlob;
    name: string;
    description: string;
    mintAuthority: string;
    collectionMintAddress: string;
    symbol: string;
}): Promise<{
    metadataUri: string;
    imageBlob: _ExternalBlob;
    name: string;
    description: string;
    mintAuthority: string;
    collectionMintAddress: string;
    symbol: string;
}> {
    return {
        metadataUri: value.metadataUri,
        imageBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.imageBlob),
        name: value.name,
        description: value.description,
        mintAuthority: value.mintAuthority,
        collectionMintAddress: value.collectionMintAddress,
        symbol: value.symbol
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: AuctionStatus;
    mintAddress?: string;
    sellerAddress?: string;
}): {
    status: [] | [_AuctionStatus];
    mintAddress: [] | [string];
    sellerAddress: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_AuctionStatus_n46(_uploadFile, _downloadFile, value.status)) : candid_none(),
        mintAddress: value.mintAddress ? candid_some(value.mintAddress) : candid_none(),
        sellerAddress: value.sellerAddress ? candid_some(value.sellerAddress) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ListingStatus__1;
    mintAddress?: string;
    sellerAddress?: string;
}): {
    status: [] | [_ListingStatus__1];
    mintAddress: [] | [string];
    sellerAddress: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_ListingStatus__1_n57(_uploadFile, _downloadFile, value.status)) : candid_none(),
        mintAddress: value.mintAddress ? candid_some(value.mintAddress) : candid_none(),
        sellerAddress: value.sellerAddress ? candid_some(value.sellerAddress) : candid_none()
    };
}
async function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadataProgramAddress: string;
    imageBlob: ExternalBlob;
    name: string;
    description: string;
    mintAddress: string;
}): Promise<{
    metadataProgramAddress: string;
    imageBlob: _ExternalBlob;
    name: string;
    description: string;
    mintAddress: string;
}> {
    return {
        metadataProgramAddress: value.metadataProgramAddress,
        imageBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.imageBlob),
        name: value.name,
        description: value.description,
        mintAddress: value.mintAddress
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageBlob: ExternalBlob;
    collectionId: string;
    name: string;
    description: string;
    attributes: Array<[string, string]>;
    mintAddress: string;
}): Promise<{
    imageBlob: _ExternalBlob;
    collectionId: string;
    name: string;
    description: string;
    attributes: Array<[string, string]>;
    mintAddress: string;
}> {
    return {
        imageBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.imageBlob),
        collectionId: value.collectionId,
        name: value.name,
        description: value.description,
        attributes: value.attributes,
        mintAddress: value.mintAddress
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.user ? {
        user: null
    } : value == Role.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuctionStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    settled: null;
} | {
    pending: null;
} | {
    ended: null;
} {
    return value == AuctionStatus.active ? {
        active: null
    } : value == AuctionStatus.cancelled ? {
        cancelled: null
    } : value == AuctionStatus.settled ? {
        settled: null
    } : value == AuctionStatus.pending ? {
        pending: null
    } : value == AuctionStatus.ended ? {
        ended: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus__1): {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    sold: null;
} {
    return value == ListingStatus__1.active ? {
        active: null
    } : value == ListingStatus__1.cancelled ? {
        cancelled: null
    } : value == ListingStatus__1.expired ? {
        expired: null
    } : value == ListingStatus__1.sold ? {
        sold: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
